### ISSUE TITLE
Sorting does not work when the column header is an icon instead of text

### ISSUE THREAD

**Issue by Millio345** [Millio345/arr-default-sort-and-filter#1]
Currently sorting only supports text headers and not icon headers.

**Comment by Millio345** [comment]
This should now be fixed in the new version 1.1. If you still have issues feel free to report them here

@tchirou

**Comment by tchirou** [comment]
Fantastic ! It works on every radarr containers, no matter the URL. Great work !

Any chance you could do the same for Sonarr v4 ? 

Thanks a lot for this.

**Comment by Millio345** [comment]
> Fantastic ! It works on every radarr containers, no matter the URL. Great work !
> 
> Any chance you could do the same for Sonarr v4 ?
> 
> Thanks a lot for this.

@tchirou An update was just published which should now support all *arr sites from Servarr. If you notice any problems with them feel free to open another issue.

**Comment by tchirou** [comment]
It works great ! Radarr and sonarr v4
I juste have one instance of sonarr which is still on v3 (a seedbox, I can't force the update) so it is still in english (my other instances are in french) and so I should use "preferred word score". I did and on the other sonar instances, weirdly enough, the arrow is here but it seems to keep sorting by the "custom format", so still great
![image](https://github.com/Millio345/arr-default-sort-and-filter/assets/6749420/cc37d21b-0aef-4321-8273-c99de8c16b84)

Thanks a lot
